### ISSUE TITLE
Exception thrown when trying to render a field.

### ISSUE THREAD

**Issue by Kasaku** [mikeedwards83/Glass.Mapper#100]
All of a sudden on a site I have running, pages were throwing errors when trying to render. This was a site that was previously running fine.

Digging into the logs, I found this nested exception when a View was being rendered:

```
Exception: System.IndexOutOfRangeException
Message: Index was outside the bounds of the array.
Source: System.Core
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at System.Collections.Generic.HashSet`1.Add(T item)
   at Glass.Mapper.Sc.DataMappers.SitecoreFieldStringMapper.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context)
   at Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapToProperty(AbstractDataMappingContext mappingContext)
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.InterfacePropertyInterceptor.LoadValues()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.InterfacePropertyInterceptor.get_Values()
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.InterfacePropertyInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IElementCookieInfoProxy.get_ButtonText()
   at ASP._Page_Views_Meta_CookieBar_cshtml.Execute() in c:\Fileserver\Sites\MySite\Website\Views\Meta\CookieBar.cshtml:line 5
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
```

It wasn't just one particular page - no pages were working, each page had a problem with a particular view (or perhaps just the first one it executed). However, they all blew up at the same place, accessing the `HashSet`.

Nothing had been changed in the site (no deployments, etc). Recycling the server brought the pages back up and running absolutely fine.

I haven't dug too deeply, but have seen suggestions of problems with using `HashSet` in multi-threaded environments. Any ideas to what might be happening here?

**Comment by cardinal252** [comment]
Confirmed for us too - our site is currently suffering with this too, it seems to be intermittent on individual servers

**Comment by mikeedwards83** [comment]
This issue as been fixed and released.
