### ISSUE TITLE
Null reference exception while mapping rendering parameters template

### ISSUE THREAD

**Issue by samcgarry** [mikeedwards83/Glass.Mapper#127]
Hi,

I'm having an issue with Glass Mapper 3.1.12.24 on Sitecore 7.2 and Web Forms For Marketers 2.4.

We are using Castle Windsor and Glass Mapper and in one particular case we have a Sitecore item which has a layout which uses a control which takes a set of rendering parameters. One of these parameters is called SerialNumberInfo.
SerialNumberInfo is a Rich Text field with source /sitecore/system/Settings/HTML Editor Profile/Rich Text Full.

Everything works fine with SerialNumberInfo if it contains a value, but if it is blank I get a mapping exception saying  'Failed to map properties on [orphan]/renderingParameters.'
The stack trace for this exception looks like this:
```
Source: Glass.Mapper
   at Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context)
   at Glass.Mapper.Sc.CastleWindsor.Pipelines.ObjectConstruction.WindsorConstruction.<>c__DisplayClass6.<Execute>b__0(Object target)
   at Glass.Mapper.Sc.CastleWindsor.Pipelines.ObjectConstruction.WindsorConstruction.Execute(ObjectConstructionArgs args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args)
   at Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext)
   at Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters)
   at Glass.Mapper.Sc.SitecoreService.CreateType[T](Item item, Boolean isLazy, Boolean inferType)
   at Glass.Mapper.Sc.ItemExtensions.GlassCast[T](Item item, ISitecoreService service, Boolean isLazy, Boolean inferType)
   at Glass.Mapper.Sc.GlassHtml.GetRenderingParameters[T](NameValueCollection parameters, ID renderParametersTemplateId)
   at Glass.Mapper.Sc.GlassHtml.GetRenderingParameters[T](String parameters, ID renderParametersTemplateId)
   at Glass.Mapper.Sc.GlassHtml.GetRenderingParameters[T](String parameters)
   at Glass.Mapper.Sc.Web.Mvc.GlassController.GetRenderingParameters[T]()
```
The inner exception looks like this:

Nested Exception

Exception: System.NullReferenceException
```
Message: Object reference not set to an instance of an object.
Source: Sitecore.Forms.Mvc
   at Sitecore.Forms.Mvc.Pipelines.Fields.AddFallbackValue.Process(RenderFieldArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.PipelineMethod.Invoke(Object[] parameters)
   at Sitecore.Pipelines.CoreProcessor.Invoke(Object[] parameters)
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args)
   at Sitecore.Web.UI.WebControls.FieldRenderer.RenderField()
   at Sitecore.Web.UI.WebControls.FieldRenderer.Render()
   at Glass.Mapper.Sc.DataMappers.SitecoreFieldStringMapper.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context)
   at Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapToProperty(AbstractDataMappingContext mappingContext)
   at Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext)
```
 Do you have any advice on what could be causing this? If it is Sitecore or WFFM I can raise a support request with them.

If you can provide debug versions of the library I can try to do some more tests.

Thanks for your help,

Stephen.

**Comment by mikeedwards83** [comment]
Stephen

Looking at your stack this is something outside of Glass.Mapper.Sc, the original error is originating from the Sitecore.Forms. 

Glass handles rendering parameters by creating a fake item that contains the parameter values and then use the standard Glass pipelines to map this fake item to the model. From looking at the code for Sitecore.Forms.Mvc it looks like the AddFallbackValue is trying to find the item in the default language.

However since this is a fake item it won't find it and therefore the item is null. ideally the AddFallbackValue should have some sort of null check.

Mike

**Comment by samcgarry** [comment]
OK thanks Mike. I'll follow this up with them.

Regards,
Stephen.
