### ISSUE TITLE
Edit Mode Not Binding Properties

### ISSUE THREAD

**Issue by geoffreysmith** [mikeedwards83/Glass.Mapper#144]
In edit mode I'm getting errors on all properties, but not in preview or live mode. They are like this:

Page editting error. Could not find property Title on type System.Object

   at Glass.Mapper.Utilities.GetGlassProperty[T,K](Expression`1 field, Context context, T model)
   at Glass.Mapper.Sc.GlassHtml.MakeEditable[T](Expression`1 field, Expression`1 standardOutput, T model, Object parameters, Context context, Database database, TextWriter writer)

All my objects are interfaces and I'm in a pretty vanilla setup. This is using the latest NuGet version. Any ideas?

**Comment by geoffreysmith** [comment]
I should mention this is only happening on interfaces, when I set it up using classes it works fine.

**Comment by mikeedwards83** [comment]
Hi

I have tested this in my solution and I am not able to replicate it.

Can you show me how you are creating the object and the rendering code?

**Comment by geoffreysmith** [comment]
Yup,

    public class EmployeePullQuoteController : Controller
    {
        private readonly ISitecoreContext _context;

        public EmployeePullQuoteController(ISitecoreContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            var model = _context.GetItem<IEmployeePullQuote>(RenderingContext.Current.Rendering.Id);

            return View("~/Views/EmployeePullQuote/Index.cshtml", model);
        }
    }

And the object, this works:

    public class IEmployeePullQuote : ISitecoreItem
    {
        public virtual string Eyebrow { get; set; }
        public virtual string PullQuote { get; set; }
        public virtual Guid SitecoreId { get; set; }
    }

This does not:

    interface IEmployeePullQuote : ISitecoreItem
    {
        string Eyebrow { get; set; }
        string PullQuote { get; set; }
        Guid SitecoreId { get; set; }
    }

**Comment by mikeedwards83** [comment]
Could you add the view cshtml file and the ISItecoreItem.

**Comment by geoffreysmith** [comment]
Ah for the interface, the SitecoreId is actually in the ISitecoreItem, looks like a bit of a copy paste error on my part. In any case:

    [SitecoreType(AutoMap = true)]
    public interface ISitecoreItem
    {
        [SitecoreId]
        Guid SitecoreId { get; set; }
    }

And:

@model IEmployeePullQuote

<section>
    <h2>@Editable(x => x.Eyebrow)</h2>
    <h2>@Editable(x => x.PullQuote)</h2>
</section>

**Comment by mikeedwards83** [comment]
Could you update the IEmployeePullQuote to remove the SitecoreId property:

interface IEmployeePullQuote : ISitecoreItem
{
    string Eyebrow { get; set; }
    string PullQuote { get; set; }

}

**Comment by geoffreysmith** [comment]
Yeah same result, in my original code the SitecoreId was on the ISitecoreItem too.

**Comment by mikeedwards83** [comment]
I have tried to replicate this again and still have not luck. Do you have the full stack trace? Could it be another model on the same page?

**Comment by hiraldesai** [comment]
@geoffreysmith -  do you have any custom pipeline processor changing default Sitecore behaviour?

@mikeedwards83 - I started experiencing the same error in our test environment since I added pipeline patch for issue https://github.com/mikeedwards83/Glass.Mapper/issues/163. 

What's really driving me crazy about this is that I can't seem to reproduce this error locally. I will keep investigating and let you know if I find anything interesting.

**Comment by hiraldesai** [comment]
I had to add an additional page editor check in the end to prevent that error from happening. I still don't know enough about the Glass internals to comment on why we get that error when creating edit frame. @mikeedwards83 might be able to clarify more.

```
 public class GetViewRendererWithItemValidation : GetViewRenderer
    {        
        protected override Renderer GetRenderer(Rendering rendering, GetRendererArgs args)
        {           
            var viewRenderer = base.GetRenderer(rendering, args) as ViewRenderer;
            if (viewRenderer == null)
                return null;

            // Ignore item check when in page editor
            if (Context.PageMode.IsPageEditor || Context.PageMode.IsPageEditorEditing)
                return viewRenderer;

            // Override renderer to null when there is an unpublished item refererenced by underlying view
            return viewRenderer.Rendering.Item != null && viewRenderer.Rendering.RenderingItem.ValueOrDefault(i => i.InnerItem) != null
                ? viewRenderer
                : null;
        }
    }
```

**Comment by hiraldesai** [comment]
Update: turns out the error is not related to the view rendering patch to the pipeline at all. Although disabling it resulted in app pool recycle (which fixes the problem temporarily) which made me think it is related. Not quite sure what causes this error anymore, any ideas @mikeedwards83 ?

**Comment by mikeedwards83** [comment]
Could you post the edit frame code?

**Comment by hiraldesai** [comment]
Here is a sample edit frame code and a sample model I'm using. Although when it breaks - it breaks all edit frames on the website and doesn't come back until after app pool recycle.

```
using (BeginEditFrame(Model, "Select Image", x => x.Image))
{
<div class="hero" style="background-image: url('@Model.Image.Src');">
... some more content ...
</div>
}
```

And model is like this:

```
public interface IStandardContent : ISitecoreTemplate
    {
        [SitecoreField("StandardContent_Title")]
        string Title { get; set; }

        [SitecoreField(""StandardContent_Intro")]
        string Intro { get; set; }

        [SitecoreField("StandardContent_Image")]
        Image Image { get; set; }
    }
    public interface ISitecoreTemplate
    {
        [SitecoreId]
        Guid Id { get; set; }        
        [SitecoreInfo(SitecoreInfoType.Path)]
        string Path { get; set; }
        [SitecoreInfo(SitecoreInfoType.TemplateName)]
        string TemplateName { get; set; }
    }
```

**Comment by hiraldesai** [comment]
Hey @mikeedwards83 - any luck with this?

**Comment by mikeedwards83** [comment]
Is it possible to have the full cshtml file that contains the edit frame? I can only assume that some how a type that is being passed is not of the expected final type.

**Comment by hiraldesai** [comment]
Turns out this was really a developer error. Someone in our team added `GlassUserControl<dynamic>` in the solution - visiting any page that has this control inserted inside would break Glass mapper across the website causing this error. We have since reverted all such controls and haven't seen this issue since.

**Comment by mikeedwards83** [comment]
Closing due to inactivity. Please reopen if this is still a problem

**Comment by geoffreysmith** [comment]
I can not reopen this issue, can you reopen this? We do not have GlassUserControl<dynamic> anywhere in our project and unlike my previous fix (changing interfaces to classes) are are still getting this. Working on getting a full stack trace. I'm not as familiar with this project and was not the original developer. Things to note that I've never done before:

- Models are all classes
- They are being passed directly through view items the project doesn't have controllers.

We are having additional developers look at it. For posterity here is the error we experiencing:

    2468 11:10:09 ERROR Failed to render field
    Exception: Glass.Mapper.MapperException
    Message: Page editting error. Could not find property Link on type System.Object
    Source: Glass.Mapper
    at Glass.Mapper.Utilities.GetGlassProperty[T,K](Expression`1 field, Context context, T model)
    at Glass.Mapper.Sc.GlassHtml.MakeEditable[T](Expression`1 field, Expression`1 standardOutput, T      model, Object parameters, Context context, Database database, TextWriter writer)

Getting a full stack trace will be difficult because we cannot reproduce it locally, and as noted above an AppPool recycle fixes it. This leads me to believe it is memory related. My current plan is to setup a server we can remote debug too, hit it with some sort of script that replicates a user editing the site and wait until we can get a better stack trace. I can privately attach the full log files from Sitecore if that would help but I do not see anything out of the ordinary.
