### ISSUE TITLE
ICacheManager not registered in Windsor.

### ISSUE THREAD

**Issue by mikeedwards83** [mikeedwards83/Glass.Mapper#146]
Hi Mike,

How are you doing! I'm seeing an error in my log files, have you seen it before?

10224 10:58:32 INFO  Started clearing all Glass.Mapper caches
10224 10:58:32 ERROR Error Clearing Glass.Mapper cache for context Default
Exception: Castle.MicroKernel.ComponentNotFoundException
Message: No component for supporting the service Glass.Mapper.Caching.ICacheManager was found
Source: Castle.Windsor
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
   at Castle.Windsor.WindsorContainer.Resolve[T]()
   at Glass.Mapper.Sc.Events.PublishEnd.GlassCacheClear.ClearCache(Object sender, EventArgs args)

We have our own components config for IoC, maybe it's conflicting with yours?

Best regards,

Dražen Janjiček

**Comment by mikeedwards83** [comment]
This is now in develop, I have also added the CacheCheck and CacheAdd tasks to the SitecoreInstaller.

**Comment by mikeedwards83** [comment]
Fixed in 4.0.2
