### ISSUE TITLE
Glass mapper failed to map URL link

### ISSUE THREAD

**Issue by Nickunj** [mikeedwards83/Glass.Mapper#150]
Hi,

Recently while working on sitecore project I encountered a problem with glass mapper mapping.

The exception details are as below,

Message : {"Failed to map property Url on IELTS.Web.IELTS.Models.Base.Link"}

Inner exception : {"Unable to cast object of type 'System.String' to type 'Glass.Mapper.Sc.Fields.Link'."}

Stack trace:

at Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context)
at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.CreateObject(ObjectConstructionArgs args)
at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.Execute(ObjectConstructionArgs args)
at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args)
at Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext)
at Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Object[] constructorParameters)
at Glass.Mapper.Sc.LazyItemEnumerable`1.<ProcessItems>d__2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Glass.Mapper.Sc.LazyItemEnumerable`1.<.ctor>b__0()
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at Glass.Mapper.Sc.LazyItemEnumerable`1.GetEnumerator()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at IELTS.Web.IELTS.Controllers.NavigationController.MobileNavigation() in c:\IDPNow\Trunk\src\IELTS.Web\IELTS\Controllers\NavigationController.cs:line 491
at lambda_method(Closure , ControllerBase , Object[] )
at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)

Target site :

{Void MapPropertiesToObject(System.Object, Glass.Mapper.IAbstractService, Glass.Mapper.AbstractTypeCreationContext)}

My code look like,

var primaryNavigationItems = context.QueryRelative<Link>(string.Format("./ancestor-or-self::*[@@templateid='{0}' or @@templateid = '{1}']/Data/Primary Navigation/*", IdpTemplates.SiteTemplateId, IdpTemplates.NetworkSiteTemplateId)).ToList();

Link Model class:

[SitecoreType(AutoMap = true)]
public class Link
{
[SitecoreId]
public virtual Guid Id { get; set; }

public virtual string Title { get; set; }

[SitecoreField("Link")]
public virtual Glass.Mapper.Sc.Fields.Link Url { get; set; }
}

Please help me resolve this issue.

Thanks

Nick

**Comment by mikeedwards83** [comment]
hi

Which version of Glass are you using?

**Comment by mikeedwards83** [comment]
Hi 

Are you able to supply the Glass version number?

**Comment by mikeedwards83** [comment]
Hi Nick

I am closing this due to a lack of response. If this is still and issue please reopen.

Mike
