### ISSUE TITLE
Sitecore 8 Update 3 and "Invalid program detected"

### ISSUE THREAD

**Issue by seinarsson** [mikeedwards83/Glass.Mapper#181]
This issue is similar to an older issue (https://github.com/mikeedwards83/Glass.Mapper/issues/96), but I haven't been able to find anything else about it.

The problem is everything works just fine on all our Dev machines, but the second we go to Test or QA servers, we start getting the error below. 

The same exact update packages are used to install the modules on all servers. As far as we can tell, there are no differences in how IIS is setup, or in the versions of .NET Framework or MVC on all the servers.

If we set the AppPool's "Enable 32-Bit Applications" setting to "True", then the code works. The problem is that breaks other parts of the site.

```
Exception: System.Web.HttpUnhandledException
Message: An unhandled exception occurred.
Source: System.Web
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Nested Exception

Exception: System.InvalidOperationException
Message: Error while rendering view: '/Areas/ArkePresentationKitBootstrap/Views/Layouts/MainLayout.cshtml'.

Source: Sitecore.Mvc
   at Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer)
   at Arke.Sitecore.PresentationKit.Bootstrap.Pipelines.RenderRendering.ExecuteRenderer.Render(Renderer renderer, TextWriter writer, RenderRenderingArgs args) in c:\a\src\Arke.Sitecore.PresentationKit.Bootstrap\Pipelines\RenderRendering\ExecuteRenderer.cs:line 39
   at Arke.Sitecore.PresentationKit.Bootstrap.Pipelines.RenderRendering.ExecuteRenderer.Process(RenderRenderingArgs args) in c:\a\src\Arke.Sitecore.PresentationKit.Bootstrap\Pipelines\RenderRendering\ExecuteRenderer.cs:line 27
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Mvc.Pipelines.PipelineService.RunPipeline[TArgs](String pipelineName, TArgs args)
   at Sitecore.Mvc.Presentation.RenderingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)

Nested Exception

Exception: System.InvalidProgramException
Message: Common Language Runtime detected an invalid program.
Source: mscorlib
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Expression`1.Compile()
   at Glass.Mapper.Utilities.<.cctor>b__f(PropertyInfo property)
   at Glass.Mapper.Configuration.AbstractPropertyConfiguration.set_PropertyInfo(PropertyInfo value)
   at Glass.Mapper.Sc.DataMappers.SitecoreFieldIEnumerableMapper.Setup(DataMapperResolverArgs args)
   at Glass.Mapper.Pipelines.DataMapperResolver.Tasks.DataMapperStandardResolverTask.Execute(DataMapperResolverArgs args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args)
   at Glass.Mapper.Context.ProcessProperties(IEnumerable`1 properties)
   at Glass.Mapper.Context.Load(IConfigurationLoader[] loaders)
   at Glass.Mapper.Sc.Pipelines.Response.GetModel.GetObject(String model, Database db, Rendering renderingItem)
   at Glass.Mapper.Sc.Pipelines.Response.GetModel.GetObject(String model, Database db, Rendering renderingItem)
   at Glass.Mapper.Sc.Pipelines.Response.GetModel.Process(GetModelArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Mvc.Pipelines.PipelineService.RunPipeline[TArgs](String pipelineName, TArgs args)
   at Sitecore.Mvc.Pipelines.PipelineService.RunPipeline[TArgs,TResult](String pipelineName, TArgs args, Func`2 resultGetter)
   at Sitecore.Mvc.Presentation.Rendering.GetModel()
   at Sitecore.Mvc.Presentation.Rendering.get_Model()
   at Sitecore.Mvc.Presentation.ViewRenderer.get_Model()
   at Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer)
```

**Comment by ericsstoll** [comment]
Building Glass.Mapper.dll from source, using your gist from https://gist.github.com/mikeedwards83/9857e9ba18af3063ae8e, solves the problem. Very similar problem reported here with CA Wily and Ninject (https://communities.ca.com/thread/241698275). Mike, I think there's something here worth digging into. It seems Ninject found a solution. Maybe you could research the change they implemented (http://www.ca.com/us/support/ca-support-online/product-content/knowledgebase-articles/tec1573975.aspx?intcmp=searchresultclick&resultnum=2). Or implement a configuration setting that would flip the getter/setter over to a non-IL version? This is affecting production sites. It would be amazing to have a supported fix.

**Comment by mikeedwards83** [comment]
@ericsstoll I think we found the code in the Gist was slower than a dynamically compile setter.

The thread for Ninject is here:

https://github.com/ninject/Ninject/issues/175

I will investigate the issue.

**Comment by ericsstoll** [comment]
I think we have narrowed this down to a CA product on their DEV/QA server that profiles applications. With that program disabled, the OOTB getter/setter works fine. I have read some articles that say once the Profiler API is invoked in .NET, IL runs a little differently. It sounds like that's what Ninject was facing as well. I just wanted to confirm for you that we're fairly certain this is related to a profiling product from CA.

**Comment by mikeedwards83** [comment]
Thanks for the info. We could provide a way to fall back to seeing properties using reflection but this would be slower.
