### ISSUE TITLE
Sitecore Glass Mapper exception - Failed to map properties

### ISSUE THREAD

**Issue by bhaveshmaniya** [mikeedwards83/Glass.Mapper#196]
Hello,

We encounter the following errors frequently during heavy traffic on our production server. We are not able to reproduce the same in local. This is Glass.Mapper version 3.0.11.23.

The specific model that is mentioned in the exception having custom property(basically GlassModel) to get the item(by using SitecoreField attribute with Setting=SitecoreFieldSettings.InferType). We have observed at that moment all models throwing exception though. The issue seems to be fixed after resetting site again. Any hints? What could be the possible reason?

ERROR Error getting item: #ItemPath# 
Exception: Glass.Mapper.MapperException 
Message: Failed to map properties on #ItemPath#. 
Source: Glass.Mapper 
at Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.CreateObject(ObjectConstructionArgs args) at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.Execute(ObjectConstructionArgs args) at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args) at Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext) at Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters) at Glass.Mapper.Sc.SitecoreService.GetItem[T](Guid id, Boolean isLazy, Boolean inferType) at xxxx.Models.ItemLookup.<>c__DisplayClass8.<>c__DisplayClassc.<T>b__2(T x)

Nested Exception

Exception: Glass.Mapper.MapperException 
Message: Failed to map property xyz on xxxx.Models.XYZ 
Source: Glass.Mapper 
at Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) Nested Exception Exception: Glass.Mapper.MapperException Message: Failed to map to property 'xyz' on type 'xxxx.Models.GlassModel' Source: Glass.Mapper at Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) at Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) at Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context)

Nested Exception

Exception: Glass.Mapper.MapperException 
Message: Failed to map field xyz with value {Guid} 
Source: Glass.Mapper.Sc 
at Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) at Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapToProperty(AbstractDataMappingContext mappingContext) at Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext)

Nested Exception

Exception: System.Threading.ThreadAbortException 
Message: Thread was being aborted. 
Source: mscorlib 
at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout) at System.Threading.ReaderWriterLockSlim.EnterMyLockSpin() at System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLockCore(TimeoutTracker timeout) at System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLock(TimeoutTracker timeout) at Castle.Core.Internal.SlimReadWriteLock.ForReadingUpgradeable(Boolean waitForLock) at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory) at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors) at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, IInterceptor[] interceptors) at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.CreateLazyObject(ObjectConstructionArgs args) at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.Execute(ObjectConstructionArgs args) at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args) at Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext) at Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters) at Glass.Mapper.Sc.DataMappers.SitecoreFieldTypeMapper.GetFieldValue(String fieldValue, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) at Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context)

**Comment by bhaveshmaniya** [comment]
Hi,

I have replied Michael Edwards questions. 
Link: https://community.sitecore.net/developers/f/8/t/2047

1.Do you know what kind of load?
Unfortunately we don’t know the perfect count.

2. Is there any indication why the threading is being aborted?
No, Here is what we need your help.

3. Are you using an IOC container? If so what is the lifecycle of the SitecoreService/SitecoreContext?
Yes, we are using Castle Windsor(Castle.Core 3.3.0 for .NETFramework v4.5). Basically ,we have created on helper method which returns object of SitecoreService/SitecoreContext and we are storing it in HttpContext.Current.Items["SitecoreService/SitecoreContext"], so it will be available for current http request.

If you want the Models structure, I can provide it, please provide me your email address.

**Comment by mikeedwards83** [comment]
This sounds very similar to https://github.com/mikeedwards83/Glass.Mapper/issues/137. Can you see if this describes what you are seeing.

**Comment by bhaveshmaniya** [comment]
Hi @mikeedwards83 Yes, it loos similar. I will try to reproduce the issue in my local box and will update you. Thank you.

**Comment by daveylad** [comment]
Fyi.. We were able to reproduce the issue locally consistently by writing a simple console app that just bombarded our local instance and recycling the App Pool

Refreshing a browser (after stopping our console app) gave us the error. 

We were also able to set breakpoint on the error.

Incidentally, re-calling the Glass initialising code fixed the problem.. Which may be useful for a quick fix. 

We are now testing with latest glass mapper

**Comment by mikeedwards83** [comment]
@daveylad  Did updating solve the problem?

**Comment by daveylad** [comment]
Hi Mike,

Sorry for the delay in getting back to you. I had fully intended to update
the issue.. But Christmas got in the way.

Yes, the update did solve the problem. Thanks

Regards
Dave
