### ISSUE TITLE
MapperException - Failed to render field

### ISSUE THREAD

**Issue by selvamhari** [mikeedwards83/Glass.Mapper#242]
Hi team,
I have tried to fetch field value. I can able to see description field value. But while run i am getting following issue. Please provide solution ASAP.

Exception: Glass.Mapper.MapperException
Message: Expression doesn't evaluate to a member x.Fields.get_Item("Description")
Source: Glass.Mapper
   at Glass.Mapper.Utilities.GetTargetObjectOfLamba[T](Expression`1 field, T model, MemberExpression& memberExpression) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Utilities.cs:line 515
   at Glass.Mapper.Sc.GlassHtml.MakeEditable[T](Expression`1 field, Expression`1 standardOutput, T model, Object parameters, Context context, Database database, TextWriter writer) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\GlassHtml.cs:line 567

**Comment by Glass-Build-Github** [comment]
Can you send the lambda expression.

**Comment by selvamhari** [comment]
foreach (var item in Model){
@Editable (item,x=> X. Field ["description"])
}

**Comment by mikeedwards83** [comment]
Hi

Glass editable does not work with native Sitecore fields or indexers. You need to map the field a property on the model, e.g.:

    public class Model{

      public virtual string Description{get;set;}
    }
