### ISSUE TITLE
Glass.Cast failing to cast basic types

### ISSUE THREAD

**Issue by JasonEspin** [mikeedwards83/Glass.Mapper#288]
Hi Mike,

I am experiencing some really strange behavior with casting in Glass.Mapper.
We are using the ISitecoreContext and in particular the:

`this._context.Cast<T>(item);`

method in an attempt to cast a Sitecore item to a class in our solution. The class and item in Sitecore were a lot more complicated and we found that when adding a component into the experience editor, the code would run perfectly fine and cast the item to the type. However, once you save the page in the experience editor is when we begin to run into issues.

The page will reload and this time around the cast will fail despite having exactly the same conditions as the first time it operated. From then on, the cast will fail every time.

We then dumbed down the Item and class to contain a single property (Rich-text) called Body and attempted to cast that but still this would fail.

Our simplified interface is as follows:

```
[SitecoreType(TemplateId = "{6961424A-AF8C-414B-A32B-DC7A867E9025}")]
    public interface IArticle : IBase
    {
        /// <summary>
        /// Gets or sets the Body
        /// </summary>
        [SitecoreField(FieldId = "{965B6B7E-D7A1-4118-B86F-8857A8CE83F4}")]
        string Body { get; set; }
 }
```

This inherits from base which is defined as follows:

```
public interface IBase
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [SitecoreId]
        Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the template id.
        /// </summary>
        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [SitecoreInfo(SitecoreInfoType.Name)]
        string Name { get; set; }

        /// <summary>
        /// Gets or sets the version.
        /// </summary>
        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; set; }

        /// <summary>
        /// Gets or sets the language.
        /// </summary>
        [SitecoreInfo(SitecoreInfoType.Language)]
        string Language { get; set; }

        /// <summary>
        /// Gets or sets the path.
        /// </summary>
        [SitecoreInfo(SitecoreInfoType.Path)]
        string Path { get; set; }
    }
```

In code, we are then trying to do the following:

```
foreach (Item tempArticle in articlesFolder})) 
            {
                try
                {
                    var article = this._context.Cast<IArticle>(tempArticle);

                    if (article == null)
                    {
                        continue;
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
               
            }
```

It is in this cast that we run into the issues. As mentioned before, the first time it is added to the page after a VS publish it will run through fine but subsequent runs will cause the cast to fail especially after saving in the Experience Editor.

The stack trace can be found below:

```
at Glass.Mapper.AbstractService.RunConfigurationPipeline(AbstractTypeCreationContext abstractTypeCreationContext) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\AbstractService.cs:line 147
   at Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\AbstractService.cs:line 131
   at Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\SitecoreService.cs:line 496
   at Glass.Mapper.Sc.SitecoreService.CreateType[T](Item item, Boolean isLazy, Boolean inferType, Object[] constructorParameters) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\SitecoreService.cs:line 476
   at Glass.Mapper.Sc.SitecoreService.CreateType[T](Item item, Boolean isLazy, Boolean inferType) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\SitecoreService.cs:line 354
   at Glass.Mapper.Sc.SitecoreService.Cast[T](Item item, Boolean isLazy, Boolean inferType) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\SitecoreService.cs:line 367
   at StarterKit.Wrappers.SitecoreRepository.Cast[T](Item item)
```

**Comment by mikeedwards83** [comment]
Hi 

Can you add the exception you received to the stack trace? Was it a null reference exception?

**Comment by mikeedwards83** [comment]
Closing due to lack of activity.
