### ISSUE TITLE
Configuration Resolver pipeline did not return a type. Has the type been loaded by Glass.Mapper. Type: System.Object

### ISSUE THREAD

**Issue by vrkmajeti** [mikeedwards83/Glass.Mapper#310]
We are using latest Glass.Mapper 4.3.4.197 (tried with 4.3.4.196 as well) along with sitecore 8.2 update 3 and getting below exception with Internal Link Field type. Please advice. Thanks.

Exception: Glass.Mapper.MapperException
Message: Failed to map field {A9241449-467A-468C-B1D6-2D1B084DB411} with value /sitecore/content/Settings/Common Text/Communications/Headquarters/Home/BeyondUNWomen
Source: Glass.Mapper.Sc
   at Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\DataMappers\AbstractSitecoreFieldMapper.cs:line 147
   at Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\AbstractDataMapper.cs:line 60

Nested Exception

Exception: System.NullReferenceException
Message: Configuration Resolver pipeline did not return a type. Has the type been loaded by Glass.Mapper. Type: System.Object
Source: Glass.Mapper
   at Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\AbstractService.cs:line 144
   at Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\SitecoreService.cs:line 506
   at Glass.Mapper.Sc.DataMappers.SitecoreFieldTypeMapper.GetFieldValue(String fieldValue, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\DataMappers\SitecoreFieldTypeMapper.cs:line 64
   at Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\DataMappers\AbstractSitecoreFieldMapper.cs:line 134

**Comment by mikeedwards83** [comment]
Hi

This is a common question we receive so I have written a page about this issue.

http://www.glass.lu/Mapper/Sc/Documentation/CommonQuestionsAndProblems/SystemObjectError

Please reopen this issue if this doesn't solve your problem.

Mike

**Comment by vrkmajeti** [comment]
Hi Mike,

You are correct that the property type is **object**. Is there a different applicable glass mapper property type for sitecore's "Internal Link" fields? Please advice.

**Comment by AimalKhanOfficial** [comment]
> Hi
> 
> This is a common question we receive so I have written a page about this issue.
> 
> http://www.glass.lu/Mapper/Sc/Documentation/CommonQuestionsAndProblems/SystemObjectError
> 
> Please reopen this issue if this doesn't solve your problem.
> 
> Mike

Your link is broken! Can you please update it? Results in a 404
