### ISSUE TITLE
Glass Mapper Issue : Service has been disposed, cannot create object

### ISSUE THREAD

**Issue by srikantrahul** [mikeedwards83/Glass.Mapper#333]
5868 13:00:50 ERROR Rendering Error 'Controller: Job. Action: JobSearchMain' ErrorID 'DCE5B71F.171101130050.ARM-SCPRODCD-G2.1.0.6505.30654)' Message 'Service has been disposed, cannot create object'
8516 13:00:50 ERROR Failed to render rendering
Exception: Glass.Mapper.MapperException
Message: Service has been disposed, cannot create object
Source: Glass.Mapper
   at Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\AbstractService.cs:line 144
   at Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\SitecoreService.cs:line 506
   at Glass.Mapper.Sc.LazyItemEnumerable`1.ProcessItems() in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\LazyItemEnumerable.cs:line 95
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Glass.Mapper.Sc.LazyItemEnumerable`1.GetEnumerator() in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\LazyItemEnumerable.cs:line 119

This issue is very frequent and can't stop the pool.

**Comment by mikeedwards83** [comment]
Hi 

As the error message details, the service has been disposed. This is normally a mismatch between the IOC lifecycle of the ISitecoreService and the life of the model that is being loaded. 

For example you have register the ISitecoreService as per request but the model is being cached for reuse on other requests. Either make sure that the service lifecycle matches the model lifecycle or turn of lazy loading on the appropriate model properties.

If you need more help solving this we can offer consultancy.

Thanks

Mike
