### ISSUE TITLE
Glassmapper Failed to map property

### ISSUE THREAD

**Issue by Astleee** [mikeedwards83/Glass.Mapper#350]
ERROR Failed to map properties on /sitecore/content/*****.
Exception: Glass.Mapper.MapperException
Message: Failed to map properties on /sitecore/content/*******.
Source: Glass.Mapper
   at Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context)
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.CreateObject(ObjectConstructionArgs args)
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.Execute(ObjectConstructionArgs args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args)
   at Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext)
   at Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters)
   at Glass.Mapper.Sc.SitecoreService.GetItem[T](Guid id, Boolean isLazy, Boolean inferType)
   at LoadLanguages()
   at Page_Load(Object sender, EventArgs e)

Nested Exception

Exception: Glass.Mapper.MapperException
Message: Failed to map property CountrySelector on Namespace.Header
Source: Glass.Mapper
   at Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context)

Nested Exception

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Glass.Mapper
   at Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context)

**Comment by mikeedwards83** [comment]
Unfortunately we are not able to diagnose issue directly from stack traces. 

Could you supply further information? If your issue is urgent then can I suggest looking at our support page for info on how you can get immediate assistance: http://www.glass.lu/Support

**Comment by mikeedwards83** [comment]
Closing due to lack of response
