### ISSUE TITLE
After installing Glass v5.2.13: Sitecore (V9.0.2) sxa's site creative design exporting not working. 

### ISSUE THREAD

**Issue by uttamkumar45** [mikeedwards83/Glass.Mapper#361]
After installing Glass v5.2.13: Sitecore (V9.0.2) sxa's site creative design exporting not working. If I disable the glass mapper config files in include folder then I can export creative exchange packages.

Here is the error displayed on sitecore which exporting creating exchange package:
  "Page /test-page-for-sxa-error contains broken renderings."

Here is the error message from the log files:
Exception: System.InvalidOperationException
Message: Error while rendering view: '/Views/SxaLayout/SxaLayout.cshtml' (model: 'Castle.Proxies.RenderingModelProxy, DynamicProxyGenAssembly2').

Source: Sitecore.Mvc
   at Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer)
   at Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Render(Renderer renderer, TextWriter writer, RenderRenderingArgs args)

Nested Exception

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Sitecore.XA.Feature.CreativeExchange
   at Sitecore.XA.Feature.CreativeExchange.Pipelines.Export.DecoratePage.AddPageId.Process(PageDecoratorArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.XA.Foundation.MarkupDecorator.Extensions.PageMarkupBuilder..ctor(IPageContext pageContext, IRendering rendering)
   at Sitecore.XA.Foundation.MarkupDecorator.Extensions.MarkupExtensions.Body(RazorExtensions helper)
   at ASP._Page_Views_SxaLayout_SxaLayout_cshtml.Execute() in c:\inetpub\wwwroot\DaltileSc.local.com\Views\SxaLayout\SxaLayout.cshtml:line 30
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer)

**Comment by mikeedwards83** [comment]
Can you see if removing the Glass processors from the mvc.GetModel pipeline fixes the problem? https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/App_Config/Include/Glass/Glass.Mapper.Sc.config#L15

**Comment by uttamkumar45** [comment]
Thanks Mike for the input, after commenting out “mvc.GetModel” SXA export packages are working fine.

Thanks & Regards,
Uttam Kumar

**Comment by criscorra** [comment]
This solved my issue with exporting for Creative Exchange also! Thanks!

**Comment by mikeedwards83** [comment]
http://www.glass.lu/mapper/documentation/Problems-SXA-Exporting
