### ISSUE TITLE
GlassMapper Current version not working with Sitecore 10.4

### ISSUE THREAD

**Issue by girishsharma008** [mikeedwards83/Glass.Mapper#464]
Hi Team,

It appears that Glass Mapper is encountering issues with Sitecore 10.4, specifically related to NullReferenceException errors when using GetRenderingParameters. This problem has been reported by several users who have noted that their previously working implementations on Sitecore 10.3 are now failing after upgrading to Sitecore 10.4.

We have notice that current glass mapper not support with Sitecore 10.4 which is recently released. 

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Sitecore.Kernel
   at Sitecore.Links.UrlBuilders.Helpers.ItemPathBuilder.GetRelativePath(Item item, SiteInfo site)
   at Sitecore.Links.UrlBuilders.Helpers.ItemPathBuilder.Build(Item item, SiteInfo site)
   at Sitecore.Links.UrlBuilders.ItemUrlBuilder.UpdateItemPathParts(Item item, UrlBuildModel model, ItemUrlBuilderOptions options)
   at Sitecore.Links.UrlBuilders.ItemUrlBuilder.Build(Item item, ItemUrlBuilderOptions options)
   at Glass.Mapper.Sc.SitecoreVersionAbstractions.GetItemUrl(Item item, UrlOptions urlOptions)
   at Glass.Mapper.Sc.DataMappers.SitecoreInfoMapper.<>c__DisplayClass7_0.<Setup>b__9(Item item, GetOptionsSc getOptions)
   at Glass.Mapper.Sc.DataMappers.SitecoreInfoMapper.MapToProperty(AbstractDataMappingContext mappingContext)
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.InterfacePropertyInterceptor.LoadValue(AbstractPropertyConfiguration propertyConfiguration)
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.InterfacePropertyInterceptor.LoadAllValues()
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.InterfacePropertyInterceptor..ctor(ObjectConstructionArgs args, LazyLoadingHelper lazyLoadingHelper)
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.CreateInterfaceTask.Execute(ObjectConstructionArgs args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.<>c__DisplayClass9_1.<.ctor>b__1(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineTask`1.Next(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineTask`1.Execute(T args)
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.Execute(ObjectConstructionArgs args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.<>c__DisplayClass9_1.<.ctor>b__1(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineTask`1.Next(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineTask`1.Execute(T args)
   at Glass.Mapper.Sc.Pipelines.ObjectConstruction.EnforcedTemplateCheck.PerformTemplateCheck(ObjectConstructionArgs args, ID templateId, SitecoreEnforceTemplate enforceTemplate)
   at Glass.Mapper.Sc.Pipelines.ObjectConstruction.EnforcedTemplateCheck.Execute(ObjectConstructionArgs args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.<>c__DisplayClass9_1.<.ctor>b__1(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineTask`1.Next(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineTask`1.Execute(T args)
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CacheCheck.CacheCheckTask.Execute(ObjectConstructionArgs args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.<>c__DisplayClass9_1.<.ctor>b__1(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineTask`1.Next(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineTask`1.Execute(T args)
   at Glass.Mapper.Sc.Pipelines.ObjectConstruction.SitecoreItemTask.Execute(ObjectConstructionArgs args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.<>c__DisplayClass9_1.<.ctor>b__1(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineTask`1.Next(T args)
   at Glass.Mapper.Sc.Pipelines.ObjectConstruction.ItemVersionCountByRevisionTask.Execute(ObjectConstructionArgs args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.<>c__DisplayClass9_1.<.ctor>b__1(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineTask`1.Next(T args)
   at Glass.Mapper.Sc.Pipelines.ObjectConstruction.NullItemTask.Execute(ObjectConstructionArgs args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.<>c__DisplayClass9_0.<.ctor>b__0(T args)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args)
   at Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext)
   at Glass.Mapper.Sc.SitecoreService.RunCreateType(Item item, GetOptions options, Dictionary`2 parameters)
   at Glass.Mapper.Sc.SitecoreService.GetItem(GetItemOptions options)
   at Glass.Mapper.Sc.SitecoreService.GetItem[T](GetItemOptions options)
   at Glass.Mapper.Sc.RenderingParametersModelFactory.CreateModel[T](NameValueCollection parameters, ID renderParametersTemplateId)
   at Glass.Mapper.Sc.GlassHtml.GetRenderingParameters[T](NameValueCollection parameters, ID renderParametersTemplateId)
   at Glass.Mapper.Sc.GlassHtml.GetRenderingParameters[T](NameValueCollection parameters)
   at Glass.Mapper.Sc.GlassHtml.GetRenderingParameters[T](String parameters)
   at Glass.Mapper.Sc.Web.Mvc.GlassHtmlMvc`1.GetRenderingParameters[T]()
   at ASP._Page_Views_Shared_Components_StatisticsBar_cshtml.Execute() in D:\Inetpub\wwwroot\sitecore104.cd\Views\Shared\Components\StatisticsBar.cshtml:line 10
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer)

Thanks
Girish

**Comment by vamshikkalagiri** [comment]
@mikeedwards83 - We are facing the same issue as well. By any chance is there a plan or an update to fix this issue?

**Comment by muso31** [comment]
Hi @Jaya21-git have you updated to 5.8.183 ?

**Comment by Jaya21-git** [comment]
Yes, I have created branch from master and no conflicts are there... But I
can see PR run failed..

Regards,
Jaya
