### ISSUE TITLE
Query on possible causes of Null reference when WriteToItem

### ISSUE THREAD

**Issue by robinsalter** [mikeedwards83/Glass.Mapper#84]
A query which you may be able to help me with. I am updating a series of pages using WriteToItem. A small number of these are failing with:
Exception: System.NullReferenceException
Message: Could not find item to save value AbstractPropertyConfiguration Property: Formats Type: BL.Data.DomainModels.GlassModels.EventExhibitionGlassModel Assembly: BL.Data.DomainModels, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Source: Glass.Mapper.Sc
   at Glass.Mapper.Sc.DataMappers.SitecoreFieldTypeMapper.SetFieldValue(Object value, SitecoreFieldConfiguration config, SitecoreDataMappingContext context)
   at Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.SetField(Field field, Object value, SitecoreFieldConfiguration config, SitecoreDataMappingContext context)
   at Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapToCms(AbstractDataMappingContext mappingContext)
   at Glass.Mapper.ExtensionMethods.ForEach[T](IEnumerable`1 list, Action`1 action)
   at Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args)
   at Glass.Mapper.Sc.SitecoreService.WriteToItem[T](T target, Item item, Boolean updateStatistics, Boolean silent)
Any suggestions would be appreciated, whilst I look for common features of these items.

**Comment by cardinal252** [comment]
I seen similar behaviour to this on occasion where the database is incorrectly resolved due to the Service being used before the Database resolver has set the context database. This can be relatively common if you are resolving your Service / SitecoreContext from an IoC container. 

Could you please check to see whether your database property is correctly set on the Service that is attempting to save the item?

**Comment by mikeedwards83** [comment]
I am closing this issue due to a lack of information from the original reporter. Please reopen with more information in the future if you see the problem reoccur.
